"""empty message

Revision ID: 49f667650ed0
Revises: cd0fa41727e2
Create Date: 2023-03-12 15:09:44.351579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f667650ed0'
down_revision = 'cd0fa41727e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_logged_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logged_in', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
